### ISSUE TITLE
Doesn't Minify Images

### ISSUE THREAD

**Issue by georgemeehan** [axetroy/vscode-imagemin#3]
I downloaded this extension and rebooted vs code and then right-clicked on an image I wanted to minify and nothing happened. I reviewed the I guess you could call it instructions but nothing explained anything there was just a GIF that showed what I already did. So, how does one get this to do it's job?

**Comment by 0x000777** [comment]
I join the question! It does not work for me with * .jpg, * .png

**Comment by axetroy** [comment]
It seems that it does not work for `Gif`.

But it should work for `jpg` and `png`

**Comment by 0x000777** [comment]
It does not work for me with * .jpg, * .png.
file changes = 0 bytes

**Comment by axetroy** [comment]
@Highter87
Try adjusting the compression parameters in settings

**Comment by 0x000777** [comment]
This is may config:

```
"imagemin.format": "$FileName.$FileExtensionName",
"imagemin.png.speed": 5,
"imagemin.jpg.progressive": true,
```

**Comment by 0x000777** [comment]
Console log:

Error: ""C:\Users\�����������.OR12\.vscode\extensions\axetroy.vscode-imagemin-0.5.1\out\vendor1\jpegtran.exe"" �� ���� ����७��� ��� ���譥�
��������, �ᯮ��塞�� �ணࠬ��� ��� ������ 䠩���.

	at notFoundError (C:\Users\Администратор.OR12\.vscode\extensions\axetroy.vscode-imagemin-0.5.1\out\index.js:1:190130)
	at verifyENOENT (C:\Users\Администратор.OR12\.vscode\extensions\axetroy.vscode-imagemin-0.5.1\out\index.js:1:190459)
	at ChildProcess.module.exports.e.emit (C:\Users\Администратор.OR12\.vscode\extensions\axetroy.vscode-imagemin-0.5.1\out\index.js:1:190314)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)



In this path: c:\Users\Администратор.OR12\.vscode\extensions\axetroy.vscode-imagemin-0.5.1\out\vendor1\, not find:jpegtran.exe. There is only a jpegtran file, without the .exe extension

upd.!
I downloaded the jpegtran.exe file on the internet. Created in the same folder and it all worked! But the same needs to be done with * .png, *.gif! The files that are there are - for Linux, not for Windows.

**Comment by markdean21** [comment]
not working on my end.
